---
- name: Ensure minikube VM is checked
  hosts: minikube
  become: true

  tasks:

    - name: Debug
      ansible.builtin.debug:
        msg:
          - "ansible_distribution: {{ ansible_facts['distribution'] }}"
          - "ansible_distribution_major_version: {{ ansible_facts['distribution_major_version'] }}"

    - name: Assert target OS
      ansible.builtin.assert:
        that:
          - ansible_facts['distribution'] == _ansible_distribution
          - ansible_facts['distribution_major_version'] | int >= _min_ansible_distribution_major_version
        fail_msg: "Playbook only suitable for OS distribution {{ _ansible_distribution }} with major version >= {{ _min_ansible_distribution_major_version }}"
        success_msg: "Yes, OS is fine"

    - name: Debug
      ansible.builtin.debug:
        msg:
          - "ansible_processor_vcpus: {{ ansible_facts['processor_vcpus'] }}"
          - "ansible_memtotal_mb: {{ ansible_facts['memtotal_mb'] }}"

    - name: Assert
      ansible.builtin.assert:
        that:
          - ansible_facts['processor_vcpus'] | int >= 4
          - ansible_facts['memtotal_mb'] | int >= 7000

...
